### ISSUE TITLE
Image upload in safari - loader keeps spinning

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#161]
To reproduce (browser: safari):
1. Log in to part-up.com
2. Go to a part-up, e.g. https://part-up.com/partups/crowdsourced-ttn-voor-arnhem-nijmegen-greater-100-gelderland-YH3jE536NXekXE46E
3. Click New message button
4. Add text
5. Click Add Photo button
6. See finder pop-up appear and select an image
7. See pop-up close and loader start spinning
8. Wait for a couple of minutes to check loader is still spinning (see screenshot)

Expected behaviour: loader spins for a couple of seconds and photo is added to message.

<img width="1440" alt="screen shot 2016-01-04 at 21 37 10" src="https://cloud.githubusercontent.com/assets/14044235/12100032/a58aff72-b32c-11e5-9421-0310a5b01ab0.png">

**Comment by ralphboeije** [comment]
@jessedvrs do you know if this fix for Edge is totally different from Safari? Cause first we fixed IE, then Safari and now Edge is reported to have the same issue.

**Comment by jessedvrs** [comment]
I only applied the fix for IE to Safari. Maybe Edge need another. Is the issue still present on Safari?

**Comment by partupadmin** [comment]
In acceptance it is fixed, the release to production had some issues. Edge probably needs another then. I'll add a new issue for it.
